# service para descrever os contêiners do projeto
services:

    # contêiner da API Flask
    pokemon_api:
        # constroi a imagem da API Flask
        build:
            # define o path de origem da build
            context: .

            # define o caminho do Dockerfile
            dockerfile: src/api_FLASK/Dockerfile

        # reinicia o contêiner automaticamente em caso de falha
        restart: always

        #define as portas que serão expostas
        ports:
            - 8000:8000

        # define o nome do contêiner/imagem
        container_name: pokemon_api_container
        image: pokemon_api_image


    # contêiner do CLI
    pokemon_cli:
        # constroi a imagem do CLI
        build:
            # define o path de origem da build
            context: .

            # define o caminho do Dockerfile
            dockerfile: src/Dockerfile

        # reinicia o contêiner automaticamente em caso de falha
        restart: always

        # garante que o CLI só comece depois da API (ordem de start)
        depends_on:
            - pokemon_api

        # necessário para permitir interação via input (stdin) e um TTY
        stdin_open: true
        tty: true

        # define o nome do contêiner/imagem
        container_name: pokemon_cli_container
        image: pokemon_cli_image


